import React from "react";

export const EditMyApp: React.FC<{editFormData: any, handleEditFormChange: any, handleCancelClick: any}> = ({editFormData, handleEditFormChange, handleCancelClick}) => {
	return(
		<tr key={editFormData.appId} >
			<td>
				<span>{editFormData.appId}</span>
			</td>
			<td>
				<span>{editFormData.updateAt}</span>
			</td>
			<td>
				<input 
					name="deliverPlaning"  
					type="text" 
					value={editFormData.deliverPlaning}
					onChange={handleEditFormChange}
				/>
					
			</td>
			<td>
				<input 
					name="goods"  
					type="text" 
					value={editFormData.goods}
					onChange={handleEditFormChange}
				/>
			</td>
			<td>
				<input 
					name="sendMethod"  
					type="text" 
					value={editFormData.sendMethod}
					onChange={handleEditFormChange}
				/>
			</td>
			<td>
				<input 
					name="city"  
					type="text" 
					value={editFormData.city}
					onChange={handleEditFormChange}
				/>
			</td>
			<td>
				<input 
					name="recipientData"  
					type="text" 
					value={editFormData.recipientData}
					onChange={handleEditFormChange}
				/>
			</td>
			<td>
				<input 
					name="payer"  
					type="text" 
					value={editFormData.payer}
					onChange={handleEditFormChange}
				/>
			</td>
			<td>
				<input 
					name="commentsSales"  
					type="text" 
					value={editFormData.commentsSales}
					onChange={handleEditFormChange}
				/>
			</td>
			<td>
				<button 
					type="submit" 
					className="btn">
						Зберегти
				</button>
				<button
					type="button"
					className="btn"
					onClick={handleCancelClick}
				>
					Назад
				</button>
			</td>
		</tr>
	)
}
